import logging
import shutil
import tempfile
import time
import uuid
from pathlib import Path

from fastapi import (
    FastAPI,
    File,
    HTTPException,
    Request,
    UploadFile,
)
from pydantic import BaseModel

from app.rag.ingest import ingest_document
from app.rag.rag_service import answer_question
from app.rag.vector_store import (
    delete_document,
    get_connection,
    list_documents,
)


# ---------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format=(
        "%(asctime)s | %(levelname)s | "
        "%(name)s | %(message)s"
    ),
)

logger = logging.getLogger("equityai-api")


# ---------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------

app = FastAPI(
    title="EquityAI RAG API",
    version="1.0.0",
)


class QuestionRequest(BaseModel):
    question: str


# ---------------------------------------------------------
# HTTP observability middleware
# ---------------------------------------------------------

@app.middleware("http")
async def observe_http_request(
    request: Request,
    call_next,
):
    """
    Add a correlation ID to every HTTP request and record
    request-level latency and status.

    The request ID is stored on request.state so downstream
    application services can use the same correlation ID.
    """

    request_id = uuid.uuid4().hex[:12]

    request.state.request_id = request_id

    start = time.perf_counter()

    try:
        response = await call_next(request)

        duration_ms = round(
            (time.perf_counter() - start) * 1000,
            2,
        )

        response.headers["X-Request-ID"] = request_id

        logger.info(
            "event=http_request "
            "request_id=%s "
            "method=%s "
            "path=%s "
            "status=%s "
            "duration_ms=%s",
            request_id,
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
        )

        return response

    except Exception:
        duration_ms = round(
            (time.perf_counter() - start) * 1000,
            2,
        )

        logger.exception(
            "event=http_request_error "
            "request_id=%s "
            "method=%s "
            "path=%s "
            "duration_ms=%s",
            request_id,
            request.method,
            request.url.path,
            duration_ms,
        )

        raise


# ---------------------------------------------------------
# Health endpoint
# ---------------------------------------------------------

@app.get("/health")
def health():
    """
    Check API and database health.
    """

    try:
        with get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute("SELECT 1;")
                cursor.fetchone()

        return {
            "status": "healthy",
            "api": "up",
            "database": "up",
        }

    except Exception:
        logger.exception(
            "Database health check failed"
        )

        raise HTTPException(
            status_code=503,
            detail="Database unavailable.",
        )


# ---------------------------------------------------------
# Ask endpoint
# ---------------------------------------------------------

@app.post("/ask")
def ask(
    payload: QuestionRequest,
    request: Request,
):
    """
    Answer a question using the EquityAI RAG pipeline.

    The HTTP request ID generated by the middleware is passed
    into the RAG service so one correlation ID traces the
    complete request.
    """

    question = payload.question.strip()

    if not question:
        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty.",
        )

    request_id = request.state.request_id

    logger.info(
        "Received question request_id=%s",
        request_id,
    )

    try:
        result = answer_question(
            question,
            request_id=request_id,
        )

        logger.info(
            "Question answered successfully "
            "request_id=%s",
            request_id,
        )

        return result

    except Exception:
        logger.exception(
            "Failed to answer question "
            "request_id=%s",
            request_id,
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "The AI service is temporarily "
                "unavailable."
            ),
        )


# ---------------------------------------------------------
# Upload document
# ---------------------------------------------------------

@app.post("/documents/upload")
def upload_document(
    file: UploadFile = File(...),
):
    """
    Upload and ingest a PDF document into the RAG system.
    """

    original_filename = Path(
        file.filename or ""
    ).name

    if not original_filename:
        raise HTTPException(
            status_code=400,
            detail="A filename is required.",
        )

    if (
        Path(original_filename).suffix.lower()
        != ".pdf"
    ):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are supported.",
        )

    temp_path = None

    try:
        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".pdf",
        ) as temp_file:

            temp_path = Path(temp_file.name)

            shutil.copyfileobj(
                file.file,
                temp_file,
            )

        logger.info(
            "Starting document ingestion: %s",
            original_filename,
        )

        stats = ingest_document(
            str(temp_path),
            document_name=original_filename,
        )

        logger.info(
            "Document ingestion completed: "
            "document=%s "
            "total_chunks=%s "
            "new_chunks=%s "
            "existing_chunks=%s "
            "inserted=%s "
            "skipped=%s",
            original_filename,
            stats.get("total_chunks"),
            stats.get("new_chunks"),
            stats.get("existing_chunks"),
            stats.get("inserted"),
            stats.get("skipped"),
        )

        return {
            "status": "success",
            **stats,
        }

    except HTTPException:
        raise

    except Exception:
        logger.exception(
            "Document ingestion failed: %s",
            original_filename,
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "Document ingestion temporarily "
                "unavailable."
            ),
        )

    finally:
        try:
            file.file.close()
        except Exception:
            pass

        if (
            temp_path is not None
            and temp_path.exists()
        ):
            try:
                temp_path.unlink()

            except OSError:
                logger.warning(
                    "Could not remove temporary file: %s",
                    temp_path,
                )


# ---------------------------------------------------------
# List documents
# ---------------------------------------------------------

@app.get("/documents")
def get_documents():
    """
    List documents currently stored in the vector database.
    """

    try:
        documents = list_documents()

        logger.info(
            "Listed %s documents",
            len(documents),
        )

        return {
            "total_documents": len(documents),
            "documents": documents,
        }

    except Exception:
        logger.exception(
            "Failed to list documents"
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "Document listing temporarily "
                "unavailable."
            ),
        )


# ---------------------------------------------------------
# Delete document
# ---------------------------------------------------------

@app.delete(
    "/documents/{document_name}"
)
def remove_document(
    document_name: str,
):
    """
    Delete all vector chunks belonging to a document.
    """

    safe_document_name = Path(
        document_name
    ).name

    if not safe_document_name:
        raise HTTPException(
            status_code=400,
            detail="Document name is required.",
        )

    try:
        deleted_chunks = delete_document(
            safe_document_name
        )

        if deleted_chunks == 0:
            raise HTTPException(
                status_code=404,
                detail="Document not found.",
            )

        logger.info(
            "Deleted document=%s chunks=%s",
            safe_document_name,
            deleted_chunks,
        )

        return {
            "status": "success",
            "document": safe_document_name,
            "deleted_chunks": deleted_chunks,
        }

    except HTTPException:
        raise

    except Exception:
        logger.exception(
            "Failed to delete document: %s",
            safe_document_name,
        )

        raise HTTPException(
            status_code=503,
            detail=(
                "Document deletion temporarily "
                "unavailable."
            ),
        )