import os
from unittest.mock import patch

from fastapi.testclient import TestClient

from app.api.main import app


TEST_API_KEY = "equityai-test-key"
os.environ["EQUITYAI_API_KEY"] = TEST_API_KEY

AUTH_HEADERS = {
    "X-API-Key": TEST_API_KEY,
}

client = TestClient(app)


@patch("app.api.main.get_connection")
def test_health(mock_get_connection):
    """
    The health endpoint should report that both
    the API and database are operational.
    """

    mock_connection = (
        mock_get_connection
        .return_value
        .__enter__
        .return_value
    )

    mock_cursor = (
        mock_connection
        .cursor
        .return_value
        .__enter__
        .return_value
    )

    mock_cursor.fetchone.return_value = (1,)

    response = client.get("/health")

    assert response.status_code == 200

    assert response.json() == {
        "status": "healthy",
        "api": "up",
        "database": "up",
    }

    mock_cursor.execute.assert_called_once_with(
        "SELECT 1;"
    )

    mock_cursor.fetchone.assert_called_once_with()


def test_empty_question():
    """
    An empty question should be rejected.
    """

    response = client.post(
        "/ask",
        headers=AUTH_HEADERS,
        json={
            "question": "   "
        },
    )

    assert response.status_code == 400

    assert response.json() == {
        "detail": "Question cannot be empty."
    }

    # Middleware should add a request ID
    # even to rejected requests.
    assert "x-request-id" in response.headers

    assert response.headers["x-request-id"]


@patch("app.api.main.answer_question")
def test_valid_question(mock_answer_question):
    """
    A valid question should return a successful
    RAG response.

    The test verifies that the HTTP request ID
    generated by the middleware is propagated
    into the RAG service.
    """

    def mock_rag_response(
        question,
        request_id=None,
    ):
        return {
            "answer": (
                "The IPO offer price is ₦525.00."
            ),
            "sources": [
                {
                    "document": (
                        "dangote_refinery_valuation.pdf"
                    ),
                    "page": 1,
                    "chunk": 1,
                    "score": 0.525,
                }
            ],
            "request_id": request_id,
        }

    mock_answer_question.side_effect = (
        mock_rag_response
    )

    response = client.post(
        "/ask",
        headers=AUTH_HEADERS,
        json={
            "question": "What is the IPO offer price?"
        },
    )

    assert response.status_code == 200

    data = response.json()

    assert (
        data["answer"]
        == "The IPO offer price is ₦525.00."
    )

    assert len(data["sources"]) == 1

    assert (
        data["sources"][0]["document"]
        == "dangote_refinery_valuation.pdf"
    )

    # -----------------------------------------
    # Verify request-ID propagation
    # -----------------------------------------

    assert "x-request-id" in response.headers

    http_request_id = (
        response.headers["x-request-id"]
    )

    assert http_request_id

    assert data["request_id"] == http_request_id

    mock_answer_question.assert_called_once_with(
        "What is the IPO offer price?",
        request_id=http_request_id,
    )


@patch("app.api.main.list_documents")
def test_list_documents(mock_list_documents):
    """
    The documents endpoint should return all
    indexed documents and their metadata.
    """

    mock_list_documents.return_value = [
        {
            "document": (
                "dangote_refinery_valuation.pdf"
            ),
            "pages": 2,
            "chunks": 9,
        },
        {
            "document": (
                "equityai_test_company.pdf"
            ),
            "pages": 1,
            "chunks": 1,
        },
    ]

    response = client.get(
        "/documents",
        headers=AUTH_HEADERS,
    )

    assert response.status_code == 200

    data = response.json()

    assert data["total_documents"] == 2

    assert len(data["documents"]) == 2

    assert (
        data["documents"][0]["document"]
        == "dangote_refinery_valuation.pdf"
    )

    assert data["documents"][0]["pages"] == 2
    assert data["documents"][0]["chunks"] == 9

    mock_list_documents.assert_called_once_with()


@patch("app.api.main.delete_document")
def test_delete_document(mock_delete_document):
    """
    Deleting an existing document should return
    the number of deleted chunks.
    """

    mock_delete_document.return_value = 1

    response = client.delete(
        "/documents/equityai_test_company.pdf",
        headers=AUTH_HEADERS,
    )

    assert response.status_code == 200

    assert response.json() == {
        "status": "success",
        "document": "equityai_test_company.pdf",
        "deleted_chunks": 1,
    }

    mock_delete_document.assert_called_once_with(
        "equityai_test_company.pdf"
    )


@patch("app.api.main.delete_document")
def test_delete_missing_document(
    mock_delete_document,
):
    """
    Deleting a document that does not exist
    should return HTTP 404.
    """

    mock_delete_document.return_value = 0

    response = client.delete(
        "/documents/missing_document.pdf",
        headers=AUTH_HEADERS,
    )

    assert response.status_code == 404

    assert response.json() == {
        "detail": "Document not found."
    }

    mock_delete_document.assert_called_once_with(
        "missing_document.pdf"
    )

def test_list_documents_requires_api_key():
    """
    Document inventory must not be publicly accessible.
    """

    response = client.get("/documents")

    assert response.status_code == 401


def test_delete_document_requires_api_key():
    """
    Document deletion must not be publicly accessible.
    """

    response = client.delete(
        "/documents/security-test-document.pdf"
    )

    assert response.status_code == 401


@patch("app.api.main.answer_question")
def test_rag_failure_returns_503(
    mock_answer_question,
):
    """
    A technical failure in the RAG pipeline should
    return HTTP 503 while preserving the HTTP
    correlation ID.
    """

    mock_answer_question.side_effect = RuntimeError(
        "Simulated RAG failure"
    )

    response = client.post(
        "/ask",
        headers=AUTH_HEADERS,
        json={
            "question": "What is the IPO offer price?"
        },
    )

    assert response.status_code == 503

    assert response.json() == {
        "detail": (
            "The AI service is temporarily "
            "unavailable."
        )
    }

    assert "x-request-id" in response.headers

    request_id = response.headers[
        "x-request-id"
    ]

    assert request_id

    mock_answer_question.assert_called_once_with(
        "What is the IPO offer price?",
        request_id=request_id,
    )

@patch("app.api.main.get_rag_metrics")
def test_rag_metrics_endpoint(
    mock_get_rag_metrics,
):
    """
    The RAG metrics endpoint should expose
    aggregate production observability data.
    """

    mock_get_rag_metrics.return_value = {
        "requests_total": 4,
        "outcomes": {
            "answered": 2,
            "abstained": 1,
            "errors": 1,
        },
        "rates": {
            "answered_pct": 50.0,
            "abstained_pct": 25.0,
            "error_pct": 25.0,
        },
        "latency_ms": {
            "embedding_ms": {
                "count": 4,
                "p50": 100.0,
                "p95": 190.0,
                "p99": 198.0,
            },
            "retrieval_ms": {
                "count": 4,
                "p50": 20.0,
                "p95": 38.0,
                "p99": 39.6,
            },
            "reranking_ms": {
                "count": 4,
                "p50": 2.0,
                "p95": 3.8,
                "p99": 3.96,
            },
            "generation_ms": {
                "count": 3,
                "p50": 4000.0,
                "p95": 4900.0,
                "p99": 4980.0,
            },
            "total_ms": {
                "count": 4,
                "p50": 4300.0,
                "p95": 5700.0,
                "p99": 5940.0,
            },
        },
    }

    response = client.get(
        "/metrics/rag"
    )

    assert response.status_code == 200

    data = response.json()

    assert data["requests_total"] == 4

    assert data["outcomes"] == {
        "answered": 2,
        "abstained": 1,
        "errors": 1,
    }

    assert data["rates"] == {
        "answered_pct": 50.0,
        "abstained_pct": 25.0,
        "error_pct": 25.0,
    }

    assert (
        data["latency_ms"]
        ["total_ms"]
        ["p50"]
        == 4300.0
    )

    assert (
        data["latency_ms"]
        ["generation_ms"]
        ["count"]
        == 3
    )

    mock_get_rag_metrics.assert_called_once_with()

@patch("app.api.main.answer_question")
def test_ask_rate_limit(mock_answer_question):
    """
    The /ask endpoint should reject requests that
    exceed 10 requests per minute per client.
    """

    from app.api.main import limiter

    limiter.reset()

    mock_answer_question.return_value = {
        "answer": "Test answer",
        "sources": [],
        "request_id": "test",
    }

    try:
        for _ in range(10):
            response = client.post(
                "/ask",
                headers=AUTH_HEADERS,
                json={
                    "question": "Rate limit test"
                },
            )

            assert response.status_code == 200

        response = client.post(
            "/ask",
            headers=AUTH_HEADERS,
            json={
                "question": "Rate limit test"
            },
        )

        assert response.status_code == 429

        assert response.json() == {
            "detail": (
                "Rate limit exceeded. "
                "Please try again later."
            )
        }

    finally:
        limiter.reset()


def test_cors_allows_equityai_frontend():
    """
    The production EquityAI frontend should be
    permitted to make browser requests to the API.
    """

    response = client.options(
        "/ask",
        headers={
            "Origin": "https://equityai.com.ng",
            "Access-Control-Request-Method": "POST",
            "Access-Control-Request-Headers": (
                "Content-Type,X-API-Key"
            ),
        },
    )

    assert response.status_code == 200

    assert (
        response.headers["access-control-allow-origin"]
        == "https://equityai.com.ng"
    )


def test_cors_rejects_unknown_origin():
    """
    An unapproved website should not receive
    CORS permission from the API.
    """

    response = client.options(
        "/ask",
        headers={
            "Origin": "https://example.com",
            "Access-Control-Request-Method": "POST",
            "Access-Control-Request-Headers": (
                "Content-Type,X-API-Key"
            ),
        },
    )

    assert (
        response.headers.get(
            "access-control-allow-origin"
        )
        is None
    )


def test_ask_uses_financial_analysis_when_available(
    monkeypatch,
):
    financial_result = {
        "answer": "FINANCIAL ANALYSIS",
        "sources": [],
        "request_id": "financial-request",
        "analysis_type": "financial",
        "complete_history": True,
        "requested_period_count": 2,
        "available_period_count": 2,
        "missing_metrics": [],
    }

    def fake_financial(
        question,
        request_id=None,
    ):
        assert "revenue" in question.lower()
        assert request_id is not None
        return {
            **financial_result,
            "request_id": request_id,
        }

    def fail_rag(*args, **kwargs):
        raise AssertionError(
            "Ordinary RAG must not run when "
            "financial analysis succeeds."
        )

    monkeypatch.setattr(
        "app.api.main."
        "answer_financial_analysis_question",
        fake_financial,
    )

    monkeypatch.setattr(
        "app.api.main.answer_question",
        fail_rag,
    )

    response = client.post(
        "/ask",
        headers=AUTH_HEADERS,
        json={
            "question": (
                "Show ABC revenue for the "
                "last 2 years."
            )
        },
    )

    assert response.status_code == 200

    body = response.json()

    assert (
        body["answer"]
        == "FINANCIAL ANALYSIS"
    )

    assert (
        body["analysis_type"]
        == "financial"
    )

    assert body["request_id"]


def test_ask_falls_back_to_existing_rag(
    monkeypatch,
):
    calls = {
        "financial": 0,
        "rag": 0,
    }

    def fake_financial(
        question,
        request_id=None,
    ):
        calls["financial"] += 1
        return None

    def fake_rag(
        question,
        request_id=None,
    ):
        calls["rag"] += 1

        return {
            "answer": "ORDINARY RAG ANSWER",
            "sources": [],
            "request_id": request_id,
        }

    monkeypatch.setattr(
        "app.api.main."
        "answer_financial_analysis_question",
        fake_financial,
    )

    monkeypatch.setattr(
        "app.api.main.answer_question",
        fake_rag,
    )

    response = client.post(
        "/ask",
        headers=AUTH_HEADERS,
        json={
            "question": (
                "What is the IPO offer price?"
            )
        },
    )

    assert response.status_code == 200

    body = response.json()

    assert (
        body["answer"]
        == "ORDINARY RAG ANSWER"
    )

    assert calls == {
        "financial": 1,
        "rag": 1,
    }

    assert body["request_id"]


@patch("app.api.main.dispatch_document_ingestion")
def test_upload_accepts_tickerless_company(
    mock_dispatch_document_ingestion,
):
    """
    Private or unlisted issuers may not have a ticker or exchange.
    The upload API must preserve that valid issuer state rather
    than rejecting the document before ingestion.
    """

    mock_dispatch_document_ingestion.return_value = {
        "document_id": (
            "11111111-1111-1111-1111-111111111111"
        ),
        "document": "dangote-report.pdf",
        "status": "queued",
        "message_id": "message-111",
    }

    response = client.post(
        "/documents/upload",
        headers=AUTH_HEADERS,
        files={
            "file": (
                "dangote-report.pdf",
                b"%PDF-1.4 test",
                "application/pdf",
            ),
        },
        data={
            "company_name": (
                "Dangote Petroleum Refinery FZE"
            ),
            "country": "Nigeria",
            "currency": "NGN",
            "report_type": "annual",
            "fiscal_year": "2025",
            "period_end": "2025-12-31",
        },
    )

    assert response.status_code == 202

    kwargs = mock_dispatch_document_ingestion.call_args.kwargs

    assert kwargs["company_name"] == (
        "Dangote Petroleum Refinery FZE"
    )
    assert kwargs["ticker"] is None
    assert kwargs["exchange"] is None


@patch("app.api.main.dispatch_document_ingestion")
def test_upload_converts_blank_ticker_and_exchange_to_none(
    mock_dispatch_document_ingestion,
):
    """
    HTML multipart forms commonly submit optional empty fields as
    empty strings. The API must normalize those values to None.
    """

    mock_dispatch_document_ingestion.return_value = {
        "document_id": (
            "22222222-2222-2222-2222-222222222222"
        ),
        "document": "private-company.pdf",
        "status": "queued",
        "message_id": "message-222",
    }

    response = client.post(
        "/documents/upload",
        headers=AUTH_HEADERS,
        files={
            "file": (
                "private-company.pdf",
                b"%PDF-1.4 test",
                "application/pdf",
            ),
        },
        data={
            "company_name": "Private Company Limited",
            "ticker": "",
            "exchange": "",
            "country": "Nigeria",
            "currency": "NGN",
            "report_type": "annual",
            "fiscal_year": "2025",
            "period_end": "2025-12-31",
        },
    )

    assert response.status_code == 202

    kwargs = mock_dispatch_document_ingestion.call_args.kwargs

    assert kwargs["ticker"] is None
    assert kwargs["exchange"] is None
